app = "eduwave-mysql"
primary_region = "sin"

[build]
  image = "mysql:8.4"

[env]
  MYSQL_DATABASE = "eduwave"
  MYSQL_USER = "eduwave"

[mounts]
  source = "mysql_data"
  destination = "/var/lib/mysql"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
